[build]
command = "yarn netlify:build"
publish = "dist"
functions = "functions-build"

[dev]
command = "vite"
port = 8888
functionsPort = 9999

# Handle SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
